sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=anabatik/the-great-random-bot

script:
  - docker build . --tag "$IMAGE_NAME"
after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master
